<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
<html lang="ja">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="Content-Style-Type" content="text/css">
<title>OpenPNE安装</title>
<link rel="stylesheet" href="./modules/setup/default.css" type="text/css">
<style type="text/css">
<!--
body {
  background-color: #fff;
  color: #000;
  margin: 0px;
  padding: 1em;
  padding-right: 2em;
}
h2 {
  margin: 1em 0 1em;
}
p.caution {
  margin: 1em;
  padding: 0.8em;
  border: solid 1px #f63;
}
pre {
  margin: 0.5em;
  padding: 1em 2em;
  background-color: #eee;
}
dl {
  margin: 1em;
}
dt {
  font-weight: bold;
}
dd {
  margin: 0 0 0.5em 1em;
}
table {
  margin: 1em;
  border-collapse: collapse;
}
th {
  background-color: #ddd;
}
th, td {
  padding: 5px 10px;
  border: solid 1px #000;
}
var {
  color: #922;
}
em {
  font-weight: bold;
  font-style: normal;
}
-->
</style>
</head>

<body>
<h1>OpenPNE安装</h1>

<div id="content">
